name: FlexPort
options:
  bundleIdPrefix: com.flexport
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: en
  xcodeVersion: "15.0"
  useBaseInternationalization: true
  
settings:
  base:
    SWIFT_VERSION: "5.9"
    INFOPLIST_FILE: Sources/FlexPort/Info.plist
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    TARGETED_DEVICE_FAMILY: "1,2"
    ENABLE_PREVIEWS: "YES"
    CODE_SIGN_STYLE: Automatic
    
targets:
  FlexPort:
    type: application
    platform: iOS
    sources:
      - Sources/FlexPort/**/*.swift
    resources:
      - Resources
    dependencies:
      - sdk: SwiftUI.framework
      - sdk: Combine.framework
      - sdk: Metal.framework
      - sdk: MetalKit.framework
      - sdk: CoreML.framework
      - sdk: CoreData.framework
      - sdk: Network.framework
      - sdk: CloudKit.framework
      - sdk: AVFoundation.framework
      - sdk: CoreHaptics.framework
      - sdk: GameplayKit.framework
      
  FlexPortTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests/FlexPortTests/**/*.swift
    dependencies:
      - target: FlexPort
      - sdk: XCTest.framework
    settings:
      base:
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/FlexPort.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/FlexPort
        BUNDLE_LOADER: $(TEST_HOST)
        
  FlexPortUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - Tests/FlexPortUITests/**/*.swift
    dependencies:
      - target: FlexPort
      - sdk: XCTest.framework
    settings:
      base:
        TEST_TARGET_NAME: FlexPort
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.flexport.game
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_STRICT_OBJC_MSGSEND: YES
        ENABLE_TESTABILITY: YES
        GCC_DYNAMIC_NO_PIC: NO
        GCC_OPTIMIZATION_LEVEL: 0
        GCC_PREPROCESSOR_DEFINITIONS:
          - DEBUG=1
          - $(inherited)
        MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
        MTL_FAST_MATH: YES
        ONLY_ACTIVE_ARCH: YES
        SWIFT_OPTIMIZATION_LEVEL: -Onone
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_COMPILATION_MODE: wholemodule
          SWIFT_OPTIMIZATION_LEVEL: -O
          
schemes:
  FlexPort:
    build:
      targets:
        FlexPort: all
        FlexPortTests: [test]
        FlexPortUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - FlexPortTests
        - FlexPortUITests
      gatherCoverageData: true
      commandLineArguments:
        - "-com.apple.CoreData.SQLDebug 1"
      environmentVariables:
        - variable: SQLITE_ENABLE_THREAD_ASSERTIONS
          value: "1"
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release